/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 * About dialog class.
 * 
 * @author Erick
 */
public class AboutDialog extends javax.swing.JDialog
{
    /**
     * Creates new form About.
     * 
     * @author Erick
     * @param parent Parent object
     */
    public AboutDialog(java.awt.Frame parent)
    {
        super(parent, true);
        
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc="Look and feel setting code">
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException e)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
        //</editor-fold>

        /* Initialize components */
        initComponents();

        // Close the dialog when Esc is pressed
        String acceptName = "accept";
        javax.swing.InputMap inputMap = super.getRootPane().getInputMap(javax.swing.JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), acceptName);
        javax.swing.ActionMap actionMap = super.getRootPane().getActionMap();
        actionMap.put(acceptName, new javax.swing.AbstractAction()
        {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e)
            {
                close();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accept = new javax.swing.JButton();
        splash = new javax.swing.JLabel();
        message = new javax.swing.JTextArea();
        author = new javax.swing.JTextArea();

        setTitle("Mosaicator");
        setName("AboutDialog"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        accept.setMnemonic('A');
        accept.setText("Aceptar");
        accept.setName("accept"); // NOI18N
        accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptActionPerformed(evt);
            }
        });

        splash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/splash.png"))); // NOI18N
        splash.setFocusable(false);
        splash.setName("splash"); // NOI18N

        message.setEditable(false);
        message.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        message.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        message.setLineWrap(true);
        message.setText("Creador de moisaicos compuesto por imágenes extraídas de un video. Cuarta asignación de la materia Procesamiento Digital de Imágenes, Centro de Computación Gráficas, Facultad de Ciencias, Universidad Central de Venezuela 2-2017.");
        message.setWrapStyleWord(true);
        message.setFocusable(false);
        message.setName("message"); // NOI18N

        author.setEditable(false);
        author.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        author.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        author.setLineWrap(true);
        author.setText("Erick Rincones\nSatoru Nakada");
        author.setWrapStyleWord(true);
        author.setFocusable(false);
        author.setName("author"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splash)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(author)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accept)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(splash)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(author, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(accept);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Dialog closed.
     * 
     * @author Erick
     * @param evt Event
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        close();
    }//GEN-LAST:event_closeDialog

    /**
     * Accept button pressed.
     * 
     * @author Erick
     * @param evt Event
     */
    private void acceptActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_acceptActionPerformed
    {//GEN-HEADEREND:event_acceptActionPerformed
        close();
    }//GEN-LAST:event_acceptActionPerformed
    
    /**
     * Close the dialog.
     * 
     * @author Erick
     */
    private void close()
    {
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept;
    private javax.swing.JTextArea author;
    private javax.swing.JTextArea message;
    private javax.swing.JLabel splash;
    // End of variables declaration//GEN-END:variables
}
