/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;

/**
 * Main window class.
 * 
 * @author Erick
 */
public class MainWindow extends javax.swing.JFrame {
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc="Look and feel setting code">
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException e)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
        //</editor-fold>
        
        /* Init and setup components */
        initComponents();
        setupComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        frameTab = new javax.swing.JPanel();
        videoPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameValue = new javax.swing.JTextField();
        pathLabel = new javax.swing.JLabel();
        pathValue = new javax.swing.JTextField();
        sizeLabel = new javax.swing.JLabel();
        sizeValue = new javax.swing.JTextField();
        formatLabel = new javax.swing.JLabel();
        formatValue = new javax.swing.JTextField();
        videoHeightLabel = new javax.swing.JLabel();
        videoHeightValue = new javax.swing.JTextField();
        videoWidthLabel = new javax.swing.JLabel();
        videoWidthValue = new javax.swing.JTextField();
        lengthLabel = new javax.swing.JLabel();
        lengthValue = new javax.swing.JTextField();
        framesLabel = new javax.swing.JLabel();
        framesValue = new javax.swing.JTextField();
        fpsLabel = new javax.swing.JLabel();
        fpsValue = new javax.swing.JTextField();
        openVideo = new javax.swing.JButton();
        frameControlPanel = new javax.swing.JPanel();
        hourLabel = new javax.swing.JLabel();
        hourValue = new javax.swing.JSpinner();
        colon1 = new javax.swing.JLabel();
        minuteValue = new javax.swing.JSpinner();
        colon2 = new javax.swing.JLabel();
        secondValue = new javax.swing.JSpinner();
        colon3 = new javax.swing.JLabel();
        milisecondValue = new javax.swing.JSpinner();
        frameLabel = new javax.swing.JLabel();
        frameValue = new javax.swing.JSpinner();
        frameSlider = new javax.swing.JSlider();
        framePreview = new javax.swing.JPanel();
        mosaicTab = new javax.swing.JPanel();
        mosaicPanel = new javax.swing.JPanel();
        splisLabel = new javax.swing.JLabel();
        splitsValue = new javax.swing.JSpinner();
        samplingLevelLabel = new javax.swing.JLabel();
        samplingLevelValue = new javax.swing.JSpinner();
        scaleLabel = new javax.swing.JLabel();
        scaleValue = new javax.swing.JSpinner();
        mosaicHeightLabel = new javax.swing.JLabel();
        mosaicHeightValue = new javax.swing.JSpinner();
        mosaicWidthLabel = new javax.swing.JLabel();
        mosaicWidthValue = new javax.swing.JSpinner();
        generate = new javax.swing.JButton();
        exportMosaicButton = new javax.swing.JButton();
        mosaicPreview = new javax.swing.JPanel();
        piecesTab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        piecesLabel = new javax.swing.JLabel();
        exportPiecesButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newFile = new javax.swing.JMenuItem();
        openFile = new javax.swing.JMenuItem();
        separator1 = new javax.swing.JPopupMenu.Separator();
        save = new javax.swing.JMenuItem();
        saveAs = new javax.swing.JMenuItem();
        separator2 = new javax.swing.JPopupMenu.Separator();
        exportMosaicMenu = new javax.swing.JMenuItem();
        exportPiecesMenu = new javax.swing.JMenuItem();
        separator3 = new javax.swing.JPopupMenu.Separator();
        close = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mosaicator");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png")).getImage());
        setMinimumSize(new java.awt.Dimension(640, 400));
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(640, 400));

        tabbedPane.setName("tabbedPane"); // NOI18N

        frameTab.setName("frameTab"); // NOI18N

        videoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Video"));
        videoPanel.setName("videoPanel"); // NOI18N
        videoPanel.setPreferredSize(new java.awt.Dimension(200, 277));

        nameLabel.setText("Nombre:");
        nameLabel.setName("nameLabel"); // NOI18N

        nameValue.setEditable(false);
        nameValue.setBorder(null);
        nameValue.setName("nameValue"); // NOI18N

        pathLabel.setText("Ubicación:");
        pathLabel.setName("pathLabel"); // NOI18N

        pathValue.setEditable(false);
        pathValue.setBorder(null);
        pathValue.setName("pathValue"); // NOI18N

        sizeLabel.setText("Tamaño:");
        sizeLabel.setName("sizeLabel"); // NOI18N

        sizeValue.setEditable(false);
        sizeValue.setBorder(null);
        sizeValue.setName("sizeValue"); // NOI18N

        formatLabel.setText("Formato:");
        formatLabel.setName("formatLabel"); // NOI18N

        formatValue.setEditable(false);
        formatValue.setBorder(null);
        formatValue.setName("formatValue"); // NOI18N

        videoHeightLabel.setText("Alto:");
        videoHeightLabel.setName("videoHeightLabel"); // NOI18N

        videoHeightValue.setEditable(false);
        videoHeightValue.setBorder(null);
        videoHeightValue.setName("videoHeightValue"); // NOI18N

        videoWidthLabel.setText("Ancho:");
        videoWidthLabel.setName("videoWidthLabel"); // NOI18N

        videoWidthValue.setEditable(false);
        videoWidthValue.setBorder(null);
        videoWidthValue.setName("videoWidthValue"); // NOI18N

        lengthLabel.setText("Diración:");
        lengthLabel.setName("lengthLabel"); // NOI18N

        lengthValue.setEditable(false);
        lengthValue.setBorder(null);
        lengthValue.setName("lengthValue"); // NOI18N

        framesLabel.setText("Cuadros:");
        framesLabel.setName("framesLabel"); // NOI18N

        framesValue.setEditable(false);
        framesValue.setBorder(null);
        framesValue.setName("pathValue"); // NOI18N

        fpsLabel.setText("Tasa de cuadros:");
        fpsLabel.setName("fpsLabel"); // NOI18N

        fpsValue.setEditable(false);
        fpsValue.setBorder(null);
        fpsValue.setName("fpsValue"); // NOI18N

        openVideo.setMnemonic('A');
        openVideo.setText("Abrir...");
        openVideo.setName("openVideo"); // NOI18N

        javax.swing.GroupLayout videoPanelLayout = new javax.swing.GroupLayout(videoPanel);
        videoPanel.setLayout(videoPanelLayout);
        videoPanelLayout.setHorizontalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fpsLabel)
                    .addComponent(framesLabel)
                    .addComponent(videoWidthLabel)
                    .addComponent(videoHeightLabel)
                    .addComponent(formatLabel)
                    .addComponent(sizeLabel)
                    .addComponent(pathLabel)
                    .addComponent(lengthLabel)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameValue, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(lengthValue)
                    .addComponent(pathValue)
                    .addComponent(sizeValue)
                    .addComponent(formatValue)
                    .addComponent(videoHeightValue)
                    .addComponent(videoWidthValue)
                    .addComponent(framesValue)
                    .addComponent(fpsValue))
                .addContainerGap())
            .addGroup(videoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(openVideo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        videoPanelLayout.setVerticalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathLabel)
                    .addComponent(pathValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeLabel)
                    .addComponent(sizeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatLabel)
                    .addComponent(formatValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(videoHeightLabel)
                    .addComponent(videoHeightValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(videoWidthLabel)
                    .addComponent(videoWidthValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthLabel)
                    .addComponent(lengthValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(framesLabel)
                    .addComponent(framesValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fpsLabel)
                    .addComponent(fpsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(openVideo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameControlPanel.setMinimumSize(new java.awt.Dimension(398, 74));
        frameControlPanel.setName("frameControlPanel"); // NOI18N

        hourLabel.setText("Tiempo:");
        hourLabel.setName("hourLabel"); // NOI18N

        hourValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        hourValue.setName("hourValue"); // NOI18N

        colon1.setText(":");
        colon1.setToolTipText("");
        colon1.setName("colon1"); // NOI18N

        minuteValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        minuteValue.setName("minuteValue"); // NOI18N

        colon2.setText(":");
        colon2.setName("colon2"); // NOI18N

        secondValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        secondValue.setName("secondValue"); // NOI18N

        colon3.setText(":");
        colon3.setName("colon3"); // NOI18N

        milisecondValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        milisecondValue.setName("milisecondValue"); // NOI18N

        frameLabel.setText("Cuadro:");
        frameLabel.setName("frameLabel"); // NOI18N

        frameValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        frameValue.setName("frameValue"); // NOI18N

        frameSlider.setValue(0);
        frameSlider.setName("frameSlider"); // NOI18N

        javax.swing.GroupLayout frameControlPanelLayout = new javax.swing.GroupLayout(frameControlPanel);
        frameControlPanel.setLayout(frameControlPanelLayout);
        frameControlPanelLayout.setHorizontalGroup(
            frameControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(frameControlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hourLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minuteValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colon2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colon3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(milisecondValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(frameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameControlPanelLayout.setVerticalGroup(
            frameControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameControlPanelLayout.createSequentialGroup()
                .addGroup(frameControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourLabel)
                    .addComponent(hourValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colon1)
                    .addComponent(colon2)
                    .addComponent(minuteValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colon3)
                    .addComponent(milisecondValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frameLabel)
                    .addComponent(frameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frameSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        framePreview.setName("framePreview"); // NOI18N

        javax.swing.GroupLayout framePreviewLayout = new javax.swing.GroupLayout(framePreview);
        framePreview.setLayout(framePreviewLayout);
        framePreviewLayout.setHorizontalGroup(
            framePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        framePreviewLayout.setVerticalGroup(
            framePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout frameTabLayout = new javax.swing.GroupLayout(frameTab);
        frameTab.setLayout(frameTabLayout);
        frameTabLayout.setHorizontalGroup(
            frameTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(videoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frameControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(framePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        frameTabLayout.setVerticalGroup(
            frameTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(videoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameTabLayout.createSequentialGroup()
                        .addComponent(framePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frameControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tabbedPane.addTab("Cuadro", frameTab);

        mosaicTab.setName("mosaicTab"); // NOI18N

        mosaicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mosaico"));
        mosaicPanel.setName("mosaicPanel"); // NOI18N
        mosaicPanel.setPreferredSize(new java.awt.Dimension(200, 277));

        splisLabel.setText("Divisiones:");
        splisLabel.setName("splitsLabel"); // NOI18N

        splitsValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        splitsValue.setName("splitsValue"); // NOI18N

        samplingLevelLabel.setText("Nivel de muestreo:");
        samplingLevelLabel.setName("samplingLevelLabel"); // NOI18N

        samplingLevelValue.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        samplingLevelValue.setName("samplingLevelValue"); // NOI18N

        scaleLabel.setText("Escalado:");
        scaleLabel.setName("scaleLabel"); // NOI18N

        scaleValue.setModel(new javax.swing.SpinnerNumberModel(1.0f, 1.0f, null, 0.1f));
        scaleValue.setName("scaleValue"); // NOI18N

        mosaicHeightLabel.setText("Alto:");
        mosaicHeightLabel.setName("mosaicHeightLabel"); // NOI18N

        mosaicHeightValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        mosaicHeightValue.setName("mosaicHeightValue"); // NOI18N

        mosaicWidthLabel.setText("Ancho");
        mosaicWidthLabel.setName("mosaicWidthLabel"); // NOI18N

        mosaicWidthValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        mosaicWidthValue.setName("mosaicWidthValue"); // NOI18N

        generate.setMnemonic('G');
        generate.setText("Generar");
        generate.setName("generate"); // NOI18N

        exportMosaicButton.setMnemonic('E');
        exportMosaicButton.setText("Exportar...");
        exportMosaicButton.setName("exportMosaicButton"); // NOI18N

        javax.swing.GroupLayout mosaicPanelLayout = new javax.swing.GroupLayout(mosaicPanel);
        mosaicPanel.setLayout(mosaicPanelLayout);
        mosaicPanelLayout.setHorizontalGroup(
            mosaicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mosaicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mosaicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(splisLabel)
                    .addComponent(mosaicHeightLabel)
                    .addComponent(mosaicWidthLabel)
                    .addComponent(samplingLevelLabel)
                    .addComponent(scaleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mosaicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(samplingLevelValue)
                    .addComponent(splitsValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mosaicWidthValue)
                    .addComponent(mosaicHeightValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scaleValue, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(mosaicPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(generate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportMosaicButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mosaicPanelLayout.setVerticalGroup(
            mosaicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mosaicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mosaicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(splisLabel)
                    .addComponent(splitsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mosaicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(samplingLevelLabel)
                    .addComponent(samplingLevelValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mosaicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scaleLabel)
                    .addComponent(scaleValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mosaicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mosaicHeightLabel)
                    .addComponent(mosaicHeightValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mosaicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mosaicWidthLabel)
                    .addComponent(mosaicWidthValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mosaicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generate)
                    .addComponent(exportMosaicButton))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        mosaicPreview.setName("mosaicPreview"); // NOI18N

        javax.swing.GroupLayout mosaicPreviewLayout = new javax.swing.GroupLayout(mosaicPreview);
        mosaicPreview.setLayout(mosaicPreviewLayout);
        mosaicPreviewLayout.setHorizontalGroup(
            mosaicPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );
        mosaicPreviewLayout.setVerticalGroup(
            mosaicPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mosaicTabLayout = new javax.swing.GroupLayout(mosaicTab);
        mosaicTab.setLayout(mosaicTabLayout);
        mosaicTabLayout.setHorizontalGroup(
            mosaicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mosaicTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mosaicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mosaicPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mosaicTabLayout.setVerticalGroup(
            mosaicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mosaicTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mosaicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mosaicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(mosaicPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Mosaico", mosaicTab);

        piecesTab.setName("piecesTab"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Piezas"));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 277));

        piecesLabel.setText("Número de piezas:");
        piecesLabel.setName("piecesLabel"); // NOI18N

        exportPiecesButton.setMnemonic('E');
        exportPiecesButton.setText("Exportar...");

        jTextField1.setEditable(false);
        jTextField1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(piecesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportPiecesButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piecesLabel)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(exportPiecesButton)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout piecesTabLayout = new javax.swing.GroupLayout(piecesTab);
        piecesTab.setLayout(piecesTabLayout);
        piecesTabLayout.setHorizontalGroup(
            piecesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piecesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );
        piecesTabLayout.setVerticalGroup(
            piecesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piecesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(piecesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Piezas", piecesTab);

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setMnemonic('A');
        fileMenu.setText("Archivo");
        fileMenu.setName("fileMenu"); // NOI18N

        newFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newFile.setMnemonic('N');
        newFile.setText("Nuevo...");
        newFile.setName("newFile"); // NOI18N
        fileMenu.add(newFile);

        openFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        openFile.setMnemonic('A');
        openFile.setText("Abrir...");
        openFile.setName("openFile"); // NOI18N
        fileMenu.add(openFile);

        separator1.setName("separator1"); // NOI18N
        fileMenu.add(separator1);

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        save.setMnemonic('G');
        save.setText("Guardar");
        save.setName("save"); // NOI18N
        fileMenu.add(save);

        saveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        saveAs.setMnemonic('u');
        saveAs.setText("Guardar como...");
        saveAs.setName("saveAs"); // NOI18N
        fileMenu.add(saveAs);

        separator2.setName("separator2"); // NOI18N
        fileMenu.add(separator2);

        exportMosaicMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        exportMosaicMenu.setMnemonic('E');
        exportMosaicMenu.setText("Exportar mosaico...");
        exportMosaicMenu.setName("exportMosaicMenu"); // NOI18N
        fileMenu.add(exportMosaicMenu);

        exportPiecesMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        exportPiecesMenu.setMnemonic('P');
        exportPiecesMenu.setText("Exportar piezas...");
        exportPiecesMenu.setName("exportPiecesMenu"); // NOI18N
        fileMenu.add(exportPiecesMenu);

        separator3.setName("separator3"); // NOI18N
        fileMenu.add(separator3);

        close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        close.setMnemonic('C');
        close.setText("Cerrar");
        close.setName("close"); // NOI18N
        fileMenu.add(close);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exit.setMnemonic('S');
        exit.setText("Salir");
        exit.setName("exit"); // NOI18N
        fileMenu.add(exit);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('y');
        helpMenu.setText("Ayuda");
        helpMenu.setName("helpMenu"); // NOI18N

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        about.setMnemonic('A');
        about.setText("Acerca de...");
        about.setName("about"); // NOI18N
        helpMenu.add(about);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Setup components.
     * 
     * @author Erick
     */
    // <editor-fold defaultstate="collapsed" desc="Setup components">
    private void setupComponents() {
        /* Menu bar */
        /* File menu */
        fileMenu.setActionCommand(fileMenu.getName());
        newFile.setActionCommand(newFile.getName());
        openFile.setActionCommand(openFile.getName());
        save.setActionCommand(save.getName());
        saveAs.setActionCommand(saveAs.getName());
        exportMosaicMenu.setActionCommand(exportMosaicMenu.getName());
        exportPiecesMenu.setActionCommand(exportPiecesMenu.getName());
        close.setActionCommand(close.getName());
        exit.setActionCommand(exit.getName());
        
        /* Help menu */
        helpMenu.setActionCommand(helpMenu.getName());
        about.setActionCommand(about.getName());
        
        /* Tabbed panel */
        /* Frame panel */
        openVideo.setActionCommand(openVideo.getName());
        
        /* Mosaic panel */
        generate.setActionCommand(generate.getName());
        exportMosaicButton.setActionCommand(exportMosaicButton.getName());
        
        /* Pieces panel */
        exportPiecesButton.setActionCommand(exportPiecesButton.getName());
    }
    // </editor-fold>
    
    /**
     * Set controller object.
     * 
     * @author Erick
     * @param controller Controller object.
     */
    // <editor-fold defaultstate="collapsed" desc="Set controller">
    public void setController(Controller controller)
    {
        /* Window */
        addWindowListener(controller);
        
        /* Menu bar */
        /* File menu */
        fileMenu.addActionListener(controller);
        newFile.addActionListener(controller);
        openFile.addActionListener(controller);
        save.addActionListener(controller);
        saveAs.addActionListener(controller);
        exportMosaicMenu.addActionListener(controller);
        exportPiecesMenu.addActionListener(controller);
        close.addActionListener(controller);
        exit.addActionListener(controller);
        
        /* Help menu  */
        helpMenu.addActionListener(controller);
        about.addActionListener(controller);
        
        /* Tabbed panel */
        /* Frame panel */
        openVideo.addActionListener(controller);
        frameValue.addChangeListener(controller);
        
        /* Mosaic panel */
        generate.addActionListener(controller);
        exportMosaicButton.addActionListener(controller);
        
        /* Pieces panel */
        exportPiecesButton.addActionListener(controller);
    }
    // </editor-fold>
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem close;
    private javax.swing.JLabel colon1;
    private javax.swing.JLabel colon2;
    private javax.swing.JLabel colon3;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton exportMosaicButton;
    private javax.swing.JMenuItem exportMosaicMenu;
    private javax.swing.JButton exportPiecesButton;
    private javax.swing.JMenuItem exportPiecesMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel formatLabel;
    private javax.swing.JTextField formatValue;
    private javax.swing.JLabel fpsLabel;
    private javax.swing.JTextField fpsValue;
    private javax.swing.JPanel frameControlPanel;
    private javax.swing.JLabel frameLabel;
    private javax.swing.JPanel framePreview;
    private javax.swing.JSlider frameSlider;
    private javax.swing.JPanel frameTab;
    private javax.swing.JSpinner frameValue;
    private javax.swing.JLabel framesLabel;
    private javax.swing.JTextField framesValue;
    private javax.swing.JButton generate;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JSpinner hourValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JTextField lengthValue;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JSpinner milisecondValue;
    private javax.swing.JSpinner minuteValue;
    private javax.swing.JLabel mosaicHeightLabel;
    private javax.swing.JSpinner mosaicHeightValue;
    private javax.swing.JPanel mosaicPanel;
    private javax.swing.JPanel mosaicPreview;
    private javax.swing.JPanel mosaicTab;
    private javax.swing.JLabel mosaicWidthLabel;
    private javax.swing.JSpinner mosaicWidthValue;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameValue;
    private javax.swing.JMenuItem newFile;
    private javax.swing.JMenuItem openFile;
    private javax.swing.JButton openVideo;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextField pathValue;
    private javax.swing.JLabel piecesLabel;
    private javax.swing.JPanel piecesTab;
    private javax.swing.JLabel samplingLevelLabel;
    private javax.swing.JSpinner samplingLevelValue;
    private javax.swing.JMenuItem save;
    private javax.swing.JMenuItem saveAs;
    private javax.swing.JLabel scaleLabel;
    private javax.swing.JSpinner scaleValue;
    private javax.swing.JSpinner secondValue;
    private javax.swing.JPopupMenu.Separator separator1;
    private javax.swing.JPopupMenu.Separator separator2;
    private javax.swing.JPopupMenu.Separator separator3;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JTextField sizeValue;
    private javax.swing.JLabel splisLabel;
    private javax.swing.JSpinner splitsValue;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel videoHeightLabel;
    private javax.swing.JTextField videoHeightValue;
    private javax.swing.JPanel videoPanel;
    private javax.swing.JLabel videoWidthLabel;
    private javax.swing.JTextField videoWidthValue;
    // End of variables declaration//GEN-END:variables
}
